# Generated by Django 4.1.1 on 2022-09-13 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(max_length=50, verbose_name='product_id')),
                ('price_id', models.CharField(max_length=50, verbose_name='price_id')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pay.item', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Stripe Product',
                'verbose_name_plural': 'Stripe Products',
            },
        ),
    ]
